### ISSUE TITLE
[Icon Request!!] Would be nice to have more context based folder icons & icons et cetra

### ISSUE THREAD

**Issue by nachiketa3299** [Breabcrumb/wobbly-icon-theme#10]
**What is the icon you would like to see added?**
Can be the name or file extension.

- folder icons for '**include**' '**bin**' '**build**' '**docs**' & would be nice to have more!!!
- CmakeList.txt
- Differenct icons for `*.cpp` & `*.h` & `*.hpp`
- Functionality to change base folder icon color (likewise, yellow)
 
**What do you want the icon to look like?**
Can be a logo image or something else!

CmakeList.txt for below with wobbly style:
![image](https://github.com/BreadcrumbIsTaken/wobbly-icon-theme/assets/46415457/e4bfac6a-a05e-4d31-af10-f5b1207ae3da)

`*.h`, `*.hpp` icon same style as `*.cpp` icon. 
Maybe purple color!

**Please provide a link to the homepage of the extension's creators/website**
Just to get more information about what I need to add :)

**Additional context**

Thank you for your extension!! this icon pack is so cute ^.^

**Comment by BreadcrumbIsTaken** [comment]
I'll work on this when I have time, thanks for the recommendations :). I don't know if I'll be able to do the custom folder colors though, but I'll look into it.

**Comment by BreadcrumbIsTaken** [comment]
Should be added in version 1.4.7

Let me know if I missed anything

**Comment by nachiketa3299** [comment]
wow so fast
thank you !!! love this icon pack so much 0.0
