### ISSUE TITLE
Love the icon theme, Would love to have .ts extension

### ISSUE THREAD

**Issue by rumanHuq** [Breabcrumb/wobbly-icon-theme#2]
As the title suggest, the more the merrier :)

**Comment by BreadcrumbIsTaken** [comment]
Thanks for the suggestion! Sorry for the late reply! I will get working on it right now and then push to github. Thanks for liking my theme! :)

**Comment by BreadcrumbIsTaken** [comment]
Ok so I just commited and published the new version with the typescript support. It looks cool in my opinion.
![image](https://user-images.githubusercontent.com/63469489/108609433-b08e7180-7382-11eb-883c-e124d9178920.png)
Thanks again for the suggestion! I will close this now.
