### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by TarunavBA** [Breabcrumb/wobbly-icon-theme#4]
Hey @BreadcrumbIsTaken using which program did you make these icons?

**Comment by BreadcrumbIsTaken** [comment]
# Hi! 
I used [GIMP](https://gimp.org) to make all the icons! One or two of them was made with Adobe Illustrator, but my subscription ran out 😄 

Hope this helps! :D

**Comment by TarunavBA** [comment]
> # Hi!
> I used [GIMP](https://gimp.org) to make all the icons! One or two of them was made with Adobe Illustrator, but my subscription ran out 😄
> 
> Hope this helps! :D

Thanks @BreadcrumbIsTaken! I just asked that I could also make such logos to integrate it into my projects. Or if possible can you make suck logos and contribute to https://github.com/LazyBugged/lazy.bugged? 😇😅

**Comment by TarunavBA** [comment]
Feel free to ask me help in making logos or icons. 😅 I'm always ready to contribute.

**Comment by TarunavBA** [comment]
> > # Hi!
> > I used [GIMP](https://gimp.org) to make all the icons! One or two of them was made with Adobe Illustrator, but my subscription ran out 😄
> > Hope this helps! :D
> 
> Thanks @BreadcrumbIsTaken! I just asked that I could also make such logos to integrate it into my projects. Or if possible can you make such logos and contribute to https://github.com/LazyBugged/lazy.bugged? 😇😅
Sorry a typo

**Comment by TarunavBA** [comment]
Hey @BreadcrumbIsTaken I have invited you to my organization bbrreeaaddccrruummbbss. Please check your inbox and accept it. We can collaborate and make our repositories there. 😅😇

**Comment by BreadcrumbIsTaken** [comment]
Sorry, but I am not really interested in joining an organization. I have things that I want to work on personally, and again, I don't really know you that well and don't really feel comfortable collaborating with someone I do not know. I hope you understand :)

**Comment by TarunavBA** [comment]
Hey @BreadcrumbIsTaken sorry for bothering you but did you use any scripts or plugins while developing these icons in gimp?

**Comment by BreadcrumbIsTaken** [comment]
I did not. Everything was just native GIMP.
