### ISSUE TITLE
TypeScript JSX

### ISSUE THREAD

**Issue by rimuy** [Breabcrumb/wobbly-icon-theme#6]
Would be nice if you added an icon for .tsx files

**Comment by BreadcrumbIsTaken** [comment]
### Sure!
I don't have access to my computer at the moment but I can try to make the icon in a few days! Thanks for taking interest in the theme :)

**Comment by BreadcrumbIsTaken** [comment]
Hey there! So I just published a new update that adds support for .tsx files. It uses the same icon as the .jsx files (which look like [this](https://github.com/BreadcrumbIsTaken/wobbly-icon-theme/blob/master/icons/jsx.svg).
If you feel like this needs changing please let me know and send the logo or a place where I can reference the icon. Thanks for the request!!!
