### ISSUE TITLE
[Icon Request!!]

### ISSUE THREAD

**Issue by atif0075** [Breabcrumb/wobbly-icon-theme#7]
**What is the icon you would like to see added?**
Vue icon for .vue files

**Comment by BreadcrumbIsTaken** [comment]
Sure! Thanks for the suggestion! I'll work on adding it when I have time. Expect it to be added within today or tomorrow. :)

**Comment by BreadcrumbIsTaken** [comment]
I just made a commit to add Vue and a new version was just published. It may take a while before it becomes available, but not very long. Thanks for the request!
