### ISSUE TITLE
[Icon Request!!]

### ISSUE THREAD

**Issue by atif0075** [Breabcrumb/wobbly-icon-theme#8]
**What is the icon you would like to see added?**
svelte, tailwind, postcss, npmrc

**Please provide a link to the homepage of the extension's creators/website**
[svelte](https://svelte.dev/)
[Tailwindcss](https://tailwindcss.com/)
[Postcss](https://postcss.org/)

**Additional context**
There are many things you can do. Like making specific folder icons for node_module,.svelte-kit,src,nuxt etc
<img width="272" alt="Screenshot 2022-12-21 at 10 53 09 AM" src="https://user-images.githubusercontent.com/64689549/208831752-01860a09-2988-48bf-b4c5-59aa207930aa.png">

**Comment by BreadcrumbIsTaken** [comment]
Thanks for the suggestions! I'll start working on them today :)

**Comment by BreadcrumbIsTaken** [comment]
Version 1.4.3 was just published with all the icons you requested :)

**Comment by atif0075** [comment]
> Version 1.4.3 was just published with all the icons you requested :)

node_modules icon don't work, maybe there is some typo mistake.

**Comment by BreadcrumbIsTaken** [comment]
> node_modules icon don't work, maybe there is some typo mistake. 

Oops, you are correct! I'll fix it right now :)

**Comment by BreadcrumbIsTaken** [comment]
New version just published. Sorry about that 😅 
Should be fixed now
