### ISSUE TITLE
[Icon Request!!]

### ISSUE THREAD

**Issue by Karwin3** [Breabcrumb/wobbly-icon-theme#9]
**What is the icon you would like to see added?**
.go 

**Please provide a link to the homepage of the extension's creators/website**
https://go.dev/

**Comment by BreadcrumbIsTaken** [comment]
Sure! I'll try and get it done by the end of the week. I'm a bit busy so please be patient 👍

**Comment by BreadcrumbIsTaken** [comment]
Should be updated on the latest version. If you want anything in the icon to be changed, let me know. Thanks for having interest in my silly little icon theme :)
